version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  back-tier:    

services:
  prometheus:
    image: prom/prometheus  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana-enterprise 
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - back-tier  
    volumes:
      - ../grafana:/var/lib/grafana
    env_file:
      - ./config.monitoring
    restart: always
  